apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llama3-8b
  annotations:
    sidecar.istio.io/inject: 'false'
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=llama3
      storageUri: hf://meta-llama/Llama-3.2-3B-Instruct
      resources:
        limits:
          cpu: "2"
          memory: 10Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 10Gi
          nvidia.com/gpu: "1"